#!/bin/bash
SCRIPT="$1-$2.js"
URL="http://cryptopals.com/sets/$1/challenges/$2/"
SUCCESSMSG="$SCRIPT looks good! Continue your path to crypto enlightenment by solving the next puzzle."
FAILMSG="Continue your path to crypto enlightenment by editing $SCRIPT. View the problem here:\n$URL\n"
if [[ -z $1 || -z $2 ]]; then
  echo "Usage: $0 SET# CHALLENGE#"
  exit 0
fi
if [[ -f $SCRIPT ]]; then
  node $SCRIPT && {
    if [[ "$?" == "0" ]]; then
      echo $SUCCESSMSG
    else
      watchy -w . -- node $SCRIPT
    fi
  }
else
  touch $SCRIPT && echo "require('assert').equal(true, false, '$FAILMSG')" > $SCRIPT
  $0 $1 $2
fi
