#!/bin/bash

function playFile() {
  SCRIPT="$1"
  SUCCESSMSG="$SCRIPT looks good! Continue your path to crypto enlightenment by solving the next puzzle."
  FAILMSG="Continue your path to crypto enlightenment by editing $SCRIPT.\n$URL\n"
  node $SCRIPT
  if [[ "$?" == "0" ]]; then
    echo $SUCCESSMSG
  else
    watchy -w . -- node $SCRIPT
  fi
}

#  touch $SCRIPT && echo "require('assert').equal(true, false, '$FAILMSG')" > $SCRIPT


if [[ ! -z $1 ]]; then
  playFile $1
else
  SCRIPTS=$(ls -1A challenges | awk '{print "challenges/"$1}')
  for script in $SCRIPTS; do
    playFile $script
  done
fi
